# Site settings
title: BY Blog
SEOTitle: 拾璃的博客 | Sydney Blog
header-img: img/post-bg-desk.jpg
email: 
description: "自此，日月光华，复旦复兮"
keyword: "Sydney, Sydney Blog, 拾璃的博客"
url: "http:///Sydney-SL.github.io"          # your host, for absolute URL
baseurl: ""      #例如，如果您的博客托管在“host/blog”上，则为“/blog”'
github_repo: "github.com/Sydney-SL" # you code repository

# 侧边栏设置
sidebar: true                           # 无论是否使用侧边栏。
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # 使用绝对 URL，看到它在 `/` 和 `/about/` 中都使用



# 社交网络设置
RSS: false
# weibo_username:     
zhihu_username:     
github_username:    Sydney-SL
facebook_username:  
jianshu_username:   
#twitter_username:   



# 构建设置
#从 2016 年开始，GitHub Pages 不再支持“pygments”。 使用“胭脂”来突出显示。
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # 如果你想自定义锚点。 查看 `post.html` 的第 181 行


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: False    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: qiubaiying.github.io    #仓库名称
  owner: qiubaiying    #github用户名
  admin: qiubaiying
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
